/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_jswinput_free: (a: number, b: number) => void;
export const jswinput_new: () => number;
export const jswinput_update: (a: number) => void;
export const jswinput_is_button_pressed: (a: number, b: number, c: number, d: number) => number;
export const jswinput_get_elapsed_ms: (a: number) => number;
export const jswinput_has_events: (a: number) => number;
export const __wbg_jsevent_free: (a: number, b: number) => void;
export const jsevent_event_type: (a: number) => [number, number];
export const jsevent_timestamp: (a: number) => number;
export const jsevent_data: (a: number) => any;
export const jsevent_button_id: (a: number) => [number, number];
export const jsevent_gamepad_id: (a: number) => [number, number];
export const __wbg_jsengine_free: (a: number, b: number) => void;
export const jsengine_new: () => [number, number, number];
export const jsengine_start: (a: number) => void;
export const jsengine_stop: (a: number) => void;
export const jsengine_is_running: (a: number) => number;
export const jsengine_update: (a: number) => [number, number];
export const jsengine_is_button_pressed: (a: number, b: number, c: number, d: number) => number;
export const jsengine_get_elapsed_time: (a: number) => number;
export const jsengine_has_events: (a: number) => number;
export const jsengine_show_events: (a: number) => any;
export const jsengine_process_internal_events: (a: number) => void;
export const __wbg_jstimer_free: (a: number, b: number) => void;
export const jstimer_new: () => number;
export const jstimer_elapsed_ms: (a: number) => number;
export const jstimer_reset: (a: number) => void;
export const __wbg_jswevent_free: (a: number, b: number) => void;
export const jswevent_new: () => number;
export const jswevent_update: (a: number) => void;
export const jswevent_has_events: (a: number) => number;
export const jswevent_event_count: (a: number) => number;
export const jswevent_push_custom_event: (a: number, b: number, c: number) => void;
export const jswevent_clear_events: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
